#!/usr/bin/env node
/* Builds v2/data.js from the live hub (index.html) so the v2 preview never
   hand-copies the curated seed. Re-run after editing seedData, RACES or
   CHECKLIST_PAGES in index.html:

     node tools/build_v2_data.js
*/
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'hub.html'), 'utf8');

function slice(startTok, endTok) {
  const s = html.indexOf(startTok);
  if (s < 0) throw new Error('hub.html: missing ' + startTok);
  const e = html.indexOf(endTok, s);
  if (e < 0) throw new Error('hub.html: missing end marker for ' + startTok);
  return html.slice(s, e);
}
function stringConst(name) {
  const m = html.match(new RegExp("const " + name + "='([^']*)'"));
  if (!m) throw new Error('hub.html: missing const ' + name);
  return m[1];
}

const seedVersion = stringConst('SEED_VERSION');

const state = {};
let n = 0;
const seedSrc = slice('function seedData(){', '/* ---------- storage ---------- */');
new Function('state', 'uid', 'defaultPromos', 'SEED_VERSION', 'console', seedSrc + '\nseedData();')(
  state, () => 's' + (n++).toString(36), () => [], seedVersion, { log() {}, warn() {}, info() {} }
);

const races = new Function(slice('const RACES=[', '];') + '];\nreturn RACES;')();

const clMatch = html.match(/const CHECKLIST_PAGES=(\{[^}]*\});/);
if (!clMatch) throw new Error('hub.html: missing CHECKLIST_PAGES');
const checklistPages = new Function('return ' + clMatch[1])();

if (!Array.isArray(state.drivers) || state.drivers.length < 50) throw new Error('seed produced too few drivers');
if (!Array.isArray(races) || races.length < 20) throw new Error('RACES looks wrong');

const driverPages = fs.readdirSync(path.join(root, 'drivers'))
  .filter(f => f.endsWith('.html')).map(f => f.replace(/\.html$/, '')).sort();

const out = {
  generatedFrom: 'hub.html',
  seedVersion,
  supabaseUrl: stringConst('SUPABASE_URL'),
  supabaseAnonKey: stringConst('SUPABASE_ANON_KEY'),
  ebayCampid: state.ebayCampid || '',
  drivers: state.drivers.map(d => ({
    id: d.id, name: d.name, abbr: d.abbr || '', team: d.team || '', number: d.number ?? null,
    color: d.color || '', rookieYear: d.rookieYear || null, tier: d.tier || null, record: d.record || null,
    top10: (d.top10 || []).map(e => ({
      card: e.card || '', grade: e.grade || '', price: e.price, date: e.date || '',
      source: e.source || '', url: e.url || '', img: e.img || ''
    }))
  })),
  feed: (state.feed || []).map(f => ({
    driver: f.driver, card: f.card || '', grade: f.grade || '', price: f.price,
    date: f.date || '', source: f.source || ''
  })),
  races: races.map(r => ({
    id: r.id, name: r.name, short: r.short, circuit: r.circuit, city: r.city,
    date: r.date, range: r.range, sprint: !!r.sprint, watch: r.watch || []
  })),
  checklistPages,
  driverPages
};

const target = path.join(root, 'index-data.js');
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target,
  '/* GENERATED by tools/build_v2_data.js from hub.html (seed ' + seedVersion + ') — do not edit by hand. */\n' +
  'window.F1CI_DATA=' + JSON.stringify(out) + ';\n');

// ---- footer link surface: keep v2's internal crawl paths in step with the hub ----
const exists = slug => fs.existsSync(path.join(root, slug.replace(/^\//, '') + '.html'))
  || fs.existsSync(path.join(root, slug.replace(/^\//, ''), 'index.html'));

const guides = [
  ['/f1-card-price-guide', 'Price guide'], ['/topps-chrome-f1-guide', 'Topps Chrome guide'],
  ['/kimi-antonelli-rookie-card-guide', 'Antonelli RC guide'], ['/f1-card-market-report', 'Market report'],
  ['/sets', 'Set checklists'], ['/shop', 'The Index Shop'], ['/consign', 'Sell a card'],
  ['/about', 'About the Index'], ['/methodology', 'Methodology'], ['/contact', 'Contact']
].filter(([u]) => exists(u));

const nameById = Object.fromEntries(out.drivers.map(d => [d.id, d.name]));
const lists = Object.entries(checklistPages)
  .filter(([, slug]) => exists('/' + slug))
  .map(([id, slug]) => [`/${slug}`, `${nameById[id] || id} checklist`])
  .sort((a, b) => a[1].localeCompare(b[1]));

const li = pairs => pairs.map(([u, label]) => `<li><a href="${u}">${label}</a></li>`).join('');
const block = `<div class="foot-more">
        <div><p class="side-h">Guides &amp; tools</p><ul>${li(guides)}</ul></div>
        <div><p class="side-h">Driver collection checklists</p><ul class="cols">${li(lists)}</ul></div>
      </div>`;

const page = path.join(root, 'index.html');
const v2Html = fs.readFileSync(page, 'utf8');
const start = '<!-- links:start -->', end = '<!-- links:end -->';
const i0 = v2Html.indexOf(start), i1 = v2Html.indexOf(end);
if (i0 < 0 || i1 < 0) throw new Error('index.html: missing links markers');
fs.writeFileSync(page, v2Html.slice(0, i0 + start.length) + block + v2Html.slice(i1));
console.log(`v2 footer: ${guides.length} guide links, ${lists.length} checklist links`);

const sales = out.drivers.reduce((a, d) => a + d.top10.length, 0);
console.log(`index-data.js: ${out.drivers.length} drivers, ${sales} curated top-10 sales, ${out.feed.length} feed sales, ${out.races.length} races, ${Object.keys(checklistPages).length} checklists, ${driverPages.length} driver pages`);
