#!/usr/bin/env node
/* Builds v2/data.js from the live hub (index.html) so the v2 preview never
   hand-copies the curated seed. Re-run after editing seedData, RACES or
   CHECKLIST_PAGES in index.html:

     node tools/build_v2_data.js
*/
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');

function slice(startTok, endTok) {
  const s = html.indexOf(startTok);
  if (s < 0) throw new Error('index.html: missing ' + startTok);
  const e = html.indexOf(endTok, s);
  if (e < 0) throw new Error('index.html: missing end marker for ' + startTok);
  return html.slice(s, e);
}
function stringConst(name) {
  const m = html.match(new RegExp("const " + name + "='([^']*)'"));
  if (!m) throw new Error('index.html: missing const ' + name);
  return m[1];
}

const seedVersion = stringConst('SEED_VERSION');

const state = {};
let n = 0;
const seedSrc = slice('function seedData(){', '/* ---------- storage ---------- */');
new Function('state', 'uid', 'defaultPromos', 'SEED_VERSION', 'console', seedSrc + '\nseedData();')(
  state, () => 's' + (n++).toString(36), () => [], seedVersion, { log() {}, warn() {}, info() {} }
);

const races = new Function(slice('const RACES=[', '];') + '];\nreturn RACES;')();

const clMatch = html.match(/const CHECKLIST_PAGES=(\{[^}]*\});/);
if (!clMatch) throw new Error('index.html: missing CHECKLIST_PAGES');
const checklistPages = new Function('return ' + clMatch[1])();

if (!Array.isArray(state.drivers) || state.drivers.length < 50) throw new Error('seed produced too few drivers');
if (!Array.isArray(races) || races.length < 20) throw new Error('RACES looks wrong');

const driverPages = fs.readdirSync(path.join(root, 'drivers'))
  .filter(f => f.endsWith('.html')).map(f => f.replace(/\.html$/, '')).sort();

const out = {
  generatedFrom: 'index.html',
  seedVersion,
  supabaseUrl: stringConst('SUPABASE_URL'),
  supabaseAnonKey: stringConst('SUPABASE_ANON_KEY'),
  ebayCampid: state.ebayCampid || '',
  drivers: state.drivers.map(d => ({
    id: d.id, name: d.name, abbr: d.abbr || '', team: d.team || '', number: d.number ?? null,
    color: d.color || '', rookieYear: d.rookieYear || null, tier: d.tier || null, record: d.record || null,
    top10: (d.top10 || []).map(e => ({
      card: e.card || '', grade: e.grade || '', price: e.price, date: e.date || '',
      source: e.source || '', url: e.url || '', img: e.img || ''
    }))
  })),
  feed: (state.feed || []).map(f => ({
    driver: f.driver, card: f.card || '', grade: f.grade || '', price: f.price,
    date: f.date || '', source: f.source || ''
  })),
  races: races.map(r => ({
    id: r.id, name: r.name, short: r.short, circuit: r.circuit, city: r.city,
    date: r.date, range: r.range, sprint: !!r.sprint, watch: r.watch || []
  })),
  checklistPages,
  driverPages
};

const target = path.join(root, 'v2', 'data.js');
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target,
  '/* GENERATED by tools/build_v2_data.js from index.html (seed ' + seedVersion + ') — do not edit by hand. */\n' +
  'window.F1CI_DATA=' + JSON.stringify(out) + ';\n');

const sales = out.drivers.reduce((a, d) => a + d.top10.length, 0);
console.log(`v2/data.js: ${out.drivers.length} drivers, ${sales} curated top-10 sales, ${out.feed.length} feed sales, ${out.races.length} races, ${Object.keys(checklistPages).length} checklists, ${driverPages.length} driver pages`);
